### ISSUE TITLE
[BUG] Turning random words into handles

### ISSUE THREAD

**Issue by ZenofyMedia** [dimdenGD/OldTweetDeck#1]
OldTweetDeck changes random words from tweets into actionable handles. Not sure what the steps are to reproduce but I started noticing it ~10 minutes after use. Has happened on multiple posts.

OldTweetDeck:
![image](https://github.com/dimdenGD/OldTweetDeck/assets/31422773/26194b18-58c4-4459-9d34-f470c1080a29)
Twitter for Web:
![image](https://github.com/dimdenGD/OldTweetDeck/assets/31422773/7916a4d1-351a-422a-8ce0-8e29c5795cf2)

**Comment by AlexzanDev** [comment]
Can confirm, it happens with "It's", "Jail", etc.

<img width="170" alt="image" src="https://github.com/dimdenGD/OldTweetDeck/assets/35893655/cd84d419-3291-46a3-aaa8-203080ccd52a">
<img width="171" alt="image" src="https://github.com/dimdenGD/OldTweetDeck/assets/35893655/6462b5bc-cd58-4714-ab84-977628382e2a">

**Comment by TheClassic36** [comment]
Also noticed this happen a few times. Here with "Chop" and "It" too.

![Screenshot_1](https://github.com/dimdenGD/OldTweetDeck/assets/24751415/96945518-89d0-4c54-8e5a-a122db173769)
![Screenshot_2](https://github.com/dimdenGD/OldTweetDeck/assets/24751415/e9e3d9f9-79df-4c6f-9f0f-453330cb23c3)
![Screenshot_3](https://github.com/dimdenGD/OldTweetDeck/assets/24751415/50c689fc-604c-4df1-b9d1-b0030aae1ce9)
![Screenshot_4](https://github.com/dimdenGD/OldTweetDeck/assets/24751415/364af611-26cd-4577-9c07-fa5675897a50)

**Comment by kaizen95** [comment]
also combinations of these. korean + space + english or number
![다운로드](https://github.com/dimdenGD/OldTweetDeck/assets/10494434/fa3732a5-ea55-45d1-bf2c-51b4f9a2642e)
![다운로드 (1)](https://github.com/dimdenGD/OldTweetDeck/assets/10494434/c1f1b195-04dd-4d9f-96df-dd6a9c4a7f86)
![다운로드 (3)](https://github.com/dimdenGD/OldTweetDeck/assets/10494434/bf55c4ff-d96c-426f-a449-fc1a923dd83e)

**Comment by dimdenGD** [comment]
I've found source of bug I can't figure out why it was happening, I commented out the line and it stopped happening and (so far) nothing broke so i'll keep it like this for now. CTRL+SHIFT+R to get updated file.
Source of bug: [bundle.js](https://tweetdeck.dimden.dev/bundle.js), line 661

**Comment by AlexzanDev** [comment]
Not sure what happened or if it's just me, but after the update (I had to clear cookies because I was stuck in the login screen) timelines are not loading and if they do, some tweets show hashtags and tags with repetitions. Sometimes links don't work (and the image link is shown).

<img width="256" alt="image" src="https://github.com/dimdenGD/OldTweetDeck/assets/35893655/8aa53b8f-14a3-4828-a0e5-415b22598523">
<img width="445" alt="image" src="https://github.com/dimdenGD/OldTweetDeck/assets/35893655/f0fb85b0-0157-4ead-b3d9-a26f4afca951">
<img width="260" alt="image" src="https://github.com/dimdenGD/OldTweetDeck/assets/35893655/aca7e6dd-67d8-41e1-bb78-f388b1f7f3a9">

**Comment by dimdenGD** [comment]
You're right about links, I just checked and it does appear for me too

**Comment by dimdenGD** [comment]
Edited the line to only ignore `user_mentions` this time, let's see how it works

**Comment by AlexzanDev** [comment]
Everything seems fine now, thank you!

**Comment by TheClassic36** [comment]
Can confirm it appears to be fixed. Thanks!
