### ISSUE TITLE
expanding tweet not working anymore

### ISSUE THREAD

**Issue by ogbrana** [dimdenGD/OldTweetDeck#124]
so bad news... :(
![Screenshot_1](https://github.com/dimdenGD/OldTweetDeck/assets/56264138/6fe7d374-1f1b-4da5-9c73-ce1d1545118d)

**Comment by ogbrana** [comment]
> so bad news... :( ![Screenshot_1](https://user-images.githubusercontent.com/56264138/270114571-6fe7d374-1f1b-4da5-9c73-ce1d1545118d.jpg)

after marked "enable bypass" on options, this function go back to work normally.

**Comment by Stochos** [comment]
**OldTweetDeck: "Expand Tweet" link missing**
<img width="252" alt="image" src="https://github.com/dimdenGD/OldTweetDeck/assets/27431568/44dd2886-36ad-4742-bd21-288ce0cdb4f5">  <img width="269" alt="image" src="https://github.com/dimdenGD/OldTweetDeck/assets/27431568/0500b111-04bb-44e4-839b-bc6887afe3fc">

https://twitter.com/AsYouNotWish/status/1706425601903759434

<img width="348" alt="image" src="https://github.com/dimdenGD/OldTweetDeck/assets/27431568/e044caf0-0606-4e7f-b744-743e552ad50f">

**Comment by unirun** [comment]
I've investigated the issue with the "Expand Tweet" button not appearing for Japanese tweets and identified a likely cause. The problem arises due to a condition in the code found here: https://github.com/dimdenGD/OldTweetDeck/blob/main/files/bundle.js#L22228.

Japanese tweets often fail to meet the condition for displaying the "Expand Tweet" button, which seems less common in languages that use space-separated words.

The issue stems from the way long tweets are truncated, indicated by the insertion of an ellipsis ("…"). For tweets under 140 characters, any text following the closest line break or space to the 140th character is omitted and replaced with "…". In Japanese tweets, where space characters are rarely used, the text is typically truncated after the last line break. According to the mentioned code, the "Expand Tweet" button is displayed when text.length is between 275 and 400, which equates to approximately 138 to 200 characters in Japanese.

Therefore, in Japanese, the "Expand Tweet" button will not appear unless, by chance, there's a line break at the 139th or 140th character, or if there are no line breaks or spaces within the first 140 characters. In English, the button won't appear if there are no spaces between the 275th and 280th characters.

We sometimes see Japanese tweets where only the first dozen characters are displayed, and the rest is truncated. This happens when there's a line break after the initial greeting, followed by text without any line breaks or spaces.

This issue seems to stem from the API used by TweetDeck. Since the data sent by Twitter is already truncated, it's impossible to determine from the data whether a tweet has been shortened. A 100% reliable solution appears unfeasible. The only practical approach might be to display the "Expand Tweet" button unconditionally whenever an ellipsis is present at the end of a tweet. Personally, I find this solution acceptable, but what are your thoughts, @dimdenGD?

**Comment by unirun** [comment]
![image](https://github.com/dimdenGD/OldTweetDeck/assets/1910506/0cf0d3ee-f48c-4bdb-812d-2ecabc60e87f)

https://twitter.com/chokudai/status/1757636430640316565

**Comment by unirun** [comment]
First and foremost, I'd like to extend my gratitude to @dimdenGD for making adjustments to accommodate Japanese tweets by changing the threshold. However, we are still facing the following issues:

In OldTweetDeck, the display appears as follows:
![image](https://github.com/dimdenGD/OldTweetDeck/assets/1910506/5e08f1f2-9516-4e04-8302-66c55adb1d28)

On the other hand, [on Twitter](https://twitter.com/chokudai/status/1757636430640316565) itself, it looks like this:
![image](https://github.com/dimdenGD/OldTweetDeck/assets/1910506/6d404f54-8b85-47a6-be65-a1945b4ab515)

The point at which Japanese tweets are truncated with "…" is very flexible, and setting a fixed threshold will almost certainly miss some cases. It would be greatly beneficial if there were an option in the settings to either adjust this threshold or to display the Expand Tweet option regardless of the character count.

**Comment by dimdenGD** [comment]
I lowered limit even more and now it shows up for this tweet
