### ISSUE TITLE
Misc

### ISSUE THREAD

**Issue by BKeyport** [dimdenGD/OldTweetDeck#270]
Misc things I've noticed: 

Report screen no longer works (Still references twitter.com) 
no image paste (don't know if that was a feature of BTD or not - haven't tried BTD on new) 
once in a while, things are misaligned to the left in buttons. The border will cover part of the text/icon. 

continue to be safe, man.

**Comment by katabame** [comment]
* **Report not working**
Yes, I can confirm it.
TweetDeck calling `https://twitter.com/i/safety/report_story?source=reportprofile&initiated_in_app=true&reported_user_id=<userId>` but getting `401 Unauthorized` due to domain difference.

* **Image can not paste from clipboard**
It's BetterTweetDeck's feature, you can get OldTweetDeck comaptible BetterTweetDeck from [here](https://github.com/dimdenGD/BetterTweetDeck/releases/tag/v4.11.3)

so now I suggest editing issue title to `Report screen not working` or something like that.
