### ISSUE TITLE
[Request] Compatablity with BetterTweetDeck

### ISSUE THREAD

**Issue by archeruwu** [dimdenGD/OldTweetDeck#5]
This extension is amazing, but it doesn't work with BetterTweetDeck, which I used a LOT of features from.

Just a simple request, that is all.

**Comment by TheClassic36** [comment]
See #2 - "You have to ask these extension developers to add support for this, I can't add it myself"

**Comment by archeruwu** [comment]
@eramdam Could this be a possibility?

**Comment by eramdam** [comment]
Posting my reply here for visibility. 
<img width="603" alt="While it would be possible I don't want to bother because for all we know the backend endpoints Old TweetDeck relies on might actually get removed pretty soon + I wouldn't feel comfortable telling people to trust a 3rd party (even if they're legit) with their Twitter creds." src="https://github.com/dimdenGD/OldTweetDeck/assets/1409924/8a342987-7d0b-4a42-8dd1-dfb7670aeddf">

**Comment by archeruwu** [comment]
Maybe someone could port it themselves.

I don't expect the legacy endpoints to last long, but BetterTW was so involved in my usual workflow that it's so strange without it.

Like, did you know Deck didn't support pasting images natively???

**Comment by GoldenLumia** [comment]
> Maybe someone could port it themselves.

I was planning on taking a look at myself if these endpoints aren't removed in the next day or two.

**Comment by archeruwu** [comment]
> 

Would love it! I'm on this trainwreck till the very end! 😭

**Comment by dimdenGD** [comment]
I've made BetterTweetDeck fork that works with this extension, see https://github.com/dimdenGD/BetterTweetDeck/
