### ISSUE TITLE
Authentication error (rate limits)

### ISSUE THREAD

**Issue by AlexzanDev** [dimdenGD/OldTweetDeck#61]
Premise: I know it's not OldTweetDeck's fault, I just wanted to create this issue to see if someone else has this problem.

OldTweetDeck can no longer access my Twitter account.

The request to the `verify_credentials.json` API endpoint fails with a 429 error. 

The error in the console: `GET https://api.twitter.com/1.1/account/verify_credentials.json 429`.

At this point I'm not sure if I have reached some new rate limit / Twitter killed the old API (as they announced early this week) and so the old TweetDeck is no longer usable.

EDIT: It works again, it seems like that you can't keep TweetDeck open for too much time now.

<img width="452" alt="image" src="https://github.com/dimdenGD/OldTweetDeck/assets/35893655/398eff92-36ac-4d54-a29a-2b96b0da49cc">

**Comment by dimdenGD** [comment]
429 error is rate limit error

**Comment by dimdenGD** [comment]
There's no mysteries here, currently Search and User columns are the only ones that I've switched to new API. It's also possible to see how many requests you have left before rate limit and when rate limit resets if you check network request headers. Tweetdeck already uses this information to decide how often request data but something breaks their timers, maybe using normal Twitter does since they now share same API

**Comment by AlexzanDev** [comment]
@Whirblewind I actually have two User columns and I noticed that they haven't been loading recently. I will try to remove them as they no longer work anyway, thanks for the tip.

I use TweetDeck a lot (I have multiple accounts, lists and activity columns) but as I always have done, so I was surprised to see this error.
